name: Main pipeline

on: [push]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest, windows-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - run: npm ci
            - run: npm run test
        env:
            CI: true
    lint:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest, windows-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - run: npm ci
            - run: npm run lint
    deploy:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest, windows-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - run: npm ci
            - run: npm run build
